name: GitHub Actions Demo
on: [push]
jobs:
  My-First-Job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hello
        run: |
          echo "Hello World"
      - name: Run python file
        run:
          pip install -r requirements.txt
          python ci.py
      - name: Get Log
        run: echo "Logs:\n${{LOG}}\n"
        env:
          LOG: ${{toJSON(github.event)}}
      - name: Print pusher name and email.
        run: echo "${{PUSHER}} pushed this, their email is ${{EMAIL}}"
        env:
          PUSHER: ${{github.event.pusher.name}}
          EMAIL: ${{github.event.pusher.name}}
        
          
        
  
